services:
  build:
    build:
      context: .
    container_name: keyball-build-container
    volumes:
      - .:/usr/src/app
    environment:
      KEYBOARD: keyball/keyball39
      KEYMAP: katotak
    working_dir: /usr/src/app
    command: bash build.sh
