services:
  qmk:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: qmk-build-container
    volumes:
      - .:/usr/src/app
    environment:
      qmkdir: qmk_firmware/keyboards/keyball
      kb: keyball/keyball39
      km: katotak
    working_dir: /usr/src/app
    command: bash qmk_build.sh
